version: '3.9'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .docker/env_vars/.env
    networks:
      - laravel

  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: app
    hostname: app
    restart: always
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
